FROM amazoncorretto:11-alpine
LABEL AUTH="DURVAL PRINTES"

VOLUME /root/api
VOLUME /root/.m2

WORKDIR /root/api
EXPOSE 9000
ENTRYPOINT ./mvnw spring-boot:run -Dspring-boot.run.profiles=dev -Dspring-boot.run.jvmArguments="$JAVA_OPTS"